// Code generated by ent, DO NOT EDIT.

package ent

import (
	"todo-handson/ent/schema"
	"todo-handson/ent/todo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoFields := schema.Todo{}.Fields()
	_ = todoFields
	// todoDescDescription is the schema descriptor for description field.
	todoDescDescription := todoFields[0].Descriptor()
	// todo.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	todo.DescriptionValidator = todoDescDescription.Validators[0].(func(string) error)
}
