name: release

on:
    push:
        branches:
            - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - id: tagpr
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  release:
    runs-on: ubuntu-latest
    needs: tagpr
    if: needs.tagpr.outputs.tag != ''
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: sh-kimura-docker-tutorial.sakuracr.jp
            username: ${{ secrets.REGISTORY_USERNAME }}
            password: ${{ secrets.REGISTORY_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: sh-kimura-docker-tutorial.sakuracr.jp/todo-handson

        - name: Deploy to Sakura AppRun
          uses: meso/sakura-apprun-action@v3
          with:
            sakura-api-key: ${{ secrets.SAKURA_API_KEY }}
            sakura-api-secret: ${{ secrets.SAKURA_API_SECRET }}
            container-registry: sh-kimura-docker-tutorial.sakuracr.jp  # MYREGISTRYを自分のレジストリ名に置き換えてください
            container-registry-user: ${{ secrets.REGISTORY_USERNAME }}
            container-registry-password: ${{ secrets.REGISTORY_PASSWORD }}
            port: 8080
