name: release

on:
  push:
    branches:
      - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      tag: ${{ steps.tagpr.outputs.tag }}   # ← ジョブの outputs を定義
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0                   # tagpr 実行には必須
      - id: tagpr
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: tagpr
    if: needs.tagpr.outputs.tag != ''       # ← これで条件判定できる
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.tagpr.outputs.tag }} # ← タグをチェックアウト
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: sh-kimura-docker-tutorial.sakuracr.jp
          username: ${{ secrets.REGISTORY_USERNAME }}
          password: ${{ secrets.REGISTORY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sh-kimura-docker-tutorial.sakuracr.jp/todo-handson

      - name: Deploy to Sakura AppRun
        uses: meso/sakura-apprun-action@v3
        with:
          sakura-api-key: ${{ secrets.SAKURA_API_KEY }}
          sakura-api-secret: ${{ secrets.SAKURA_API_SECRET }}
          container-registry: sh-kimura-docker-tutorial.sakuracr.jp
          container-registry-user: ${{ secrets.REGISTORY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTORY_PASSWORD }}
          port: 8080
